### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by not-ivy** [not-ivy/meowsys#1]
- [ ] use `CostMatrix` to change preferred path
- [ ] Remember most often used path
- [ ] Remember source and target so don't have to find every time
- [ ] avoid recalculating path, only when old path is broken or map change or something
